name: Test from github actions

on:
  pull_request:
    paths:
      # - '!.github/workflows/**'
      # - '!.github/CODEOWNERS'
      - '!package.json'
      - '!.buildkite/pipeline.yml'


jobs:
    test-job:
      name: "PR gatekeeper"
      runs-on: ubuntu-latest
      steps:
      - name: Trigger Buildkite Pipeline
        uses: buildkite/trigger-pipeline-action@v1.2.0
        env:
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_TOKEN }}
          BRANCH: ${GITHUB_REF}
          PIPELINE: 'wix-mobile-oss/test-project'
